server:
  type: simple
  applicationContextPath: /
  adminContextPath: /admin
  connector:
    type: http
    port: 8080

  requestLog:
    timeZone: UTC
    appenders:
      - type: console

logging:
  level: INFO
  appenders:
    - type: console
      threshold: ALL
      timeZone: UTC
      logFormat: "%-5p [%d{ISO8601,UTC}] %c: %X %marker %m%n%rEx"

metrics:
  reporters:
#      - type: console
#        frequency: 1 minute
    - type: graphite
      host: dabe343d.carbon.hostedgraphite.com
      port: 2003
      includes:
        - org.apache.http.client.*
      useRegexFilters: true
      prefix: ${graphite-api-key:-apikey}.api.ft.com.router.monitor

#metrics:
#  reporters:
#    - type: graphite
#      host: graphite.ft.com
#      port: 2003
#      frequency: 1 minute
#      prefix: membership.router.latencymonitor.heroku-prod.svc.web
#      includes:
#        - org.apache.http.client.*
#      useRegexFilters: true

jerseyClient:
  timeout: 30s
  connectionTimeout: 5s

scheduler:
  periodInSeconds: 30
  initialDelayInSeconds: 5


